// Pricing page content (EN). Translations to ru/de/pl pending.

export const PRICING_FAQ = [
  { q: 'How do I start?', a: 'Start with the Free Pilot: sign in to the Webappski portal and set up Typelessity there — step by step, or with your own AI filling it in. Every tier — Free Pilot (€0), Starter (€39/mo), Pro (€149/mo) and Enterprise (€399/mo) — starts with the free pilot.' },
  { q: 'What does the Free Pilot include?', a: 'Up to 50 submissions/month, full access to every feature (25+ languages, voice input, enrichment APIs, custom branding, webhook integration), and support by email. It is intended for risk-free evaluation on a real site.' },
  { q: 'How are paid plans different?', a: 'Starter (€39/mo, up to 500 submissions/month, up to 5 websites). Pro (€149/mo, up to 2,000 submissions/month, up to 10 websites). Enterprise (€399/mo, up to 6,000 submissions/month, unlimited websites; a named contact and other contract terms agreed on request). All plans share the same engine and the same support by email; the tier defines the submission volume and the number of websites.' },
  { q: 'How does setup work?', a: 'Setup is a wizard in the Webappski portal that you complete yourself. Step by step: Your business → Questions → Data & delivery → Messages → Review → Install. Or let your own AI write it: copy our instructions into ChatGPT or Claude with your API docs and paste the answer back (Your business → Your AI’s answer → Review → Install). Before you publish you can try the widget as a customer; the Install step gives you the embed code for your platform.' },
  { q: 'Do you charge per booking, per session, or per AI call?', a: 'Paid tiers are structured per submission volume per month — no per-AI-call surprises. We absorb GPT cost variance.' },
  { q: 'Can I run my own GPT key?', a: 'No. Typelessity runs every conversation through its own OpenAI account; using your own OpenAI key or another AI provider is not offered.' },
  { q: 'What happens if GPT is down?', a: 'The model call is retried once. If it still fails, the widget stays in the chat and asks the visitor for the next field directly; there is no separate form mode. Enrichment failures are non-fatal — the AI continues with whatever data it has.' },
  { q: 'Do you store user input?', a: 'Yes, in the EU. An abandoned conversation is deleted within 48 hours of the visitor\'s last message; one that led to a booking is kept until you ask us to erase it, by written instruction to info@webappski.com. No data is used for model training.' },
  { q: 'Is there a commitment?', a: 'No. Pilot is free and capped at 50 submissions/month. Paid plans bill monthly with no long-term commitment; other terms are by contract, on request.' },
] as const satisfies readonly { q: string; a: string }[];
